/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAuthenticatedRouteImport } from './routes/dashboard/_authenticated'
import { Route as DashboardAuthenticatedIndexRouteImport } from './routes/dashboard/_authenticated/index'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthenticatedRoute = DashboardAuthenticatedRouteImport.update({
  id: '/dashboard/_authenticated',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthenticatedIndexRoute =
  DashboardAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof DashboardAuthenticatedRouteWithChildren
  '/dashboard/': typeof DashboardAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof DashboardAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/_authenticated': typeof DashboardAuthenticatedRouteWithChildren
  '/dashboard/_authenticated/': typeof DashboardAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-up' | '/dashboard' | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-up' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/sign-up'
    | '/dashboard/_authenticated'
    | '/dashboard/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignUpRoute: typeof SignUpRoute
  DashboardAuthenticatedRoute: typeof DashboardAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authenticated': {
      id: '/dashboard/_authenticated'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_authenticated/': {
      id: '/dashboard/_authenticated/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardAuthenticatedIndexRouteImport
      parentRoute: typeof DashboardAuthenticatedRoute
    }
  }
}

interface DashboardAuthenticatedRouteChildren {
  DashboardAuthenticatedIndexRoute: typeof DashboardAuthenticatedIndexRoute
}

const DashboardAuthenticatedRouteChildren: DashboardAuthenticatedRouteChildren =
  {
    DashboardAuthenticatedIndexRoute: DashboardAuthenticatedIndexRoute,
  }

const DashboardAuthenticatedRouteWithChildren =
  DashboardAuthenticatedRoute._addFileChildren(
    DashboardAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignUpRoute: SignUpRoute,
  DashboardAuthenticatedRoute: DashboardAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
