/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as appDashboardAuthenticatedRouteImport } from './routes/(app)/dashboard/_authenticated'
import { Route as appDashboardAuthenticatedIndexRouteImport } from './routes/(app)/dashboard/_authenticated/index'
import { Route as appDashboardAuthenticatedOrdersIndexRouteImport } from './routes/(app)/dashboard/_authenticated/orders/index'
import { Route as appDashboardAuthenticatedOrdersOrderIdIndexRouteImport } from './routes/(app)/dashboard/_authenticated/orders/$orderId/index'

const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardAuthenticatedRoute =
  appDashboardAuthenticatedRouteImport.update({
    id: '/(app)/dashboard/_authenticated',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const appDashboardAuthenticatedIndexRoute =
  appDashboardAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appDashboardAuthenticatedRoute,
  } as any)
const appDashboardAuthenticatedOrdersIndexRoute =
  appDashboardAuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => appDashboardAuthenticatedRoute,
  } as any)
const appDashboardAuthenticatedOrdersOrderIdIndexRoute =
  appDashboardAuthenticatedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => appDashboardAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-up': typeof authSignUpRoute
  '/': typeof authIndexRoute
  '/dashboard': typeof appDashboardAuthenticatedRouteWithChildren
  '/dashboard/': typeof appDashboardAuthenticatedIndexRoute
  '/dashboard/orders/': typeof appDashboardAuthenticatedOrdersIndexRoute
  '/dashboard/orders/$orderId/': typeof appDashboardAuthenticatedOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-up': typeof authSignUpRoute
  '/': typeof authIndexRoute
  '/dashboard': typeof appDashboardAuthenticatedIndexRoute
  '/dashboard/orders': typeof appDashboardAuthenticatedOrdersIndexRoute
  '/dashboard/orders/$orderId': typeof appDashboardAuthenticatedOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/dashboard/_authenticated': typeof appDashboardAuthenticatedRouteWithChildren
  '/(app)/dashboard/_authenticated/': typeof appDashboardAuthenticatedIndexRoute
  '/(app)/dashboard/_authenticated/orders/': typeof appDashboardAuthenticatedOrdersIndexRoute
  '/(app)/dashboard/_authenticated/orders/$orderId/': typeof appDashboardAuthenticatedOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-up'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/orders/'
    | '/dashboard/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-up'
    | '/'
    | '/dashboard'
    | '/dashboard/orders'
    | '/dashboard/orders/$orderId'
  id:
    | '__root__'
    | '/(auth)/sign-up'
    | '/(auth)/'
    | '/(app)/dashboard/_authenticated'
    | '/(app)/dashboard/_authenticated/'
    | '/(app)/dashboard/_authenticated/orders/'
    | '/(app)/dashboard/_authenticated/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authSignUpRoute: typeof authSignUpRoute
  authIndexRoute: typeof authIndexRoute
  appDashboardAuthenticatedRoute: typeof appDashboardAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/_authenticated': {
      id: '/(app)/dashboard/_authenticated'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/_authenticated/': {
      id: '/(app)/dashboard/_authenticated/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardAuthenticatedIndexRouteImport
      parentRoute: typeof appDashboardAuthenticatedRoute
    }
    '/(app)/dashboard/_authenticated/orders/': {
      id: '/(app)/dashboard/_authenticated/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof appDashboardAuthenticatedOrdersIndexRouteImport
      parentRoute: typeof appDashboardAuthenticatedRoute
    }
    '/(app)/dashboard/_authenticated/orders/$orderId/': {
      id: '/(app)/dashboard/_authenticated/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/dashboard/orders/$orderId/'
      preLoaderRoute: typeof appDashboardAuthenticatedOrdersOrderIdIndexRouteImport
      parentRoute: typeof appDashboardAuthenticatedRoute
    }
  }
}

interface appDashboardAuthenticatedRouteChildren {
  appDashboardAuthenticatedIndexRoute: typeof appDashboardAuthenticatedIndexRoute
  appDashboardAuthenticatedOrdersIndexRoute: typeof appDashboardAuthenticatedOrdersIndexRoute
  appDashboardAuthenticatedOrdersOrderIdIndexRoute: typeof appDashboardAuthenticatedOrdersOrderIdIndexRoute
}

const appDashboardAuthenticatedRouteChildren: appDashboardAuthenticatedRouteChildren =
  {
    appDashboardAuthenticatedIndexRoute: appDashboardAuthenticatedIndexRoute,
    appDashboardAuthenticatedOrdersIndexRoute:
      appDashboardAuthenticatedOrdersIndexRoute,
    appDashboardAuthenticatedOrdersOrderIdIndexRoute:
      appDashboardAuthenticatedOrdersOrderIdIndexRoute,
  }

const appDashboardAuthenticatedRouteWithChildren =
  appDashboardAuthenticatedRoute._addFileChildren(
    appDashboardAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authSignUpRoute: authSignUpRoute,
  authIndexRoute: authIndexRoute,
  appDashboardAuthenticatedRoute: appDashboardAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
